{{- if and .Values.server.token (not .Values.server.existingTokenSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "osiris-web.fullname" . }}
  labels:
    {{- include "osiris-web.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.server.token | quote }}
{{- end -}}
